# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "One" ]
  pull_request:
    branches: [ "three" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@verse4to9

      # Runs a single command using the runners shell
      - name: Run a three-lines script
        run: echo Hello, world! Whatsupp My country advanced more

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script there are 10
        run: |
          echo Add other actions to develop,
          echo test, and deploy your projectOne.
